## [作業重點]
使用 Sklearn 中的 Lasso, Ridge 模型，來訓練各種資料集，務必了解送進去模型訓練的**資料型態**為何，也請了解模型中各項參數的意義。

機器學習的模型非常多種，但要訓練的資料多半有固定的格式，確保你了解訓練資料的格式為何，這樣在應用新模型時，就能夠最快的上手開始訓練！

## 練習時間
試著使用 sklearn datasets 的其他資料集 (boston, ...)，來訓練自己的線性迴歸模型，並加上適當的正則化來觀察訓練情形。

In [2]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score, accuracy_score

In [3]:
# 讀取資料集
wine = datasets.load_wine()

# 切分訓練集/測試集
x_train, x_test, y_train, y_test = train_test_split(wine.data, wine.target, test_size=0.3 )

# 建立一個線性回歸模型
LogR=linear_model.LogisticRegression()

# 將訓練資料丟進去模型訓練

LogR.fit(x_train, y_train)

# 將測試資料丟進模型得到預測結果
y_pred = LogR.predict(x_test)


C:\Users\Shuchun\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Shuchun\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


In [4]:
acc = accuracy_score(y_test, y_pred)
print("Accuracy: ", acc)

Accuracy:  0.9444444444444444


In [29]:
LogR.coef_

array([[-1.01969332e-01,  8.91876421e-01,  3.11118251e-01,
        -1.14604817e+00, -9.31252312e-02,  4.92050768e-01,
         9.59326606e-01, -6.76826189e-02,  1.56603410e-01,
         1.65959879e-02, -1.69247707e-01,  7.38780440e-01,
         3.02769695e-02],
       [ 6.12908258e-01, -9.77188979e-01, -5.21605196e-01,
         3.93413047e-01,  1.65618904e-02,  3.03607619e-01,
         2.51408942e-01,  3.63216216e-01,  5.68858245e-01,
        -1.70588756e+00,  6.83368461e-01,  2.69293270e-01,
        -1.47475218e-02],
       [-3.29022308e-01,  5.15715617e-01,  2.57727218e-02,
         9.00786566e-02,  2.18136108e-02, -7.32862362e-01,
        -1.66075254e+00, -7.28762693e-02, -5.84196716e-01,
         1.04450873e+00, -4.70820948e-01, -1.21353367e+00,
         8.14893272e-04]])

In [12]:
print('Mean squared error: %.2f' %mean_squared_error(y_test, y_pred))


Mean squared error: 0.36


In [20]:
'''
LASSO
'''

# 讀取資料集
wine = datasets.load_wine()

# 切分訓練集/測試集
x_train, x_test, y_train, y_test = train_test_split(wine.data, wine.target, test_size=0.3 )

# 建立一個線性回歸模型
lasso=linear_model.Lasso(alpha=1)

# 將訓練資料丟進去模型訓練

lasso.fit(x_train, y_train)

# 將測試資料丟進模型得到預測結果
y_pred = lasso.predict(x_test)


In [21]:
lasso.coef_

array([ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
       -0.        , -0.        ,  0.        , -0.        ,  0.        ,
       -0.        , -0.        , -0.00150988])

In [22]:
print('Mean squared error: %.2f' %mean_squared_error(y_test, y_pred))

Mean squared error: 0.44


In [49]:
'''
Ridge
'''
# 讀取資料集
wine = datasets.load_wine()

# 切分訓練集/測試集
x_train, x_test, y_train, y_test = train_test_split(wine.data, wine.target, test_size=0.3 )

# 建立一個線性回歸模型
ridge=linear_model.Ridge(alpha=1)

# 將訓練資料丟進去模型訓練

ridge.fit(x_train, y_train)

# 將測試資料丟進模型得到預測結果
y_pred = ridge.predict(x_test)



In [50]:
ridge.coef_

array([-1.04975097e-01,  2.62861866e-02, -1.06298573e-01,  4.37151541e-02,
       -5.08704077e-06,  1.17974704e-01, -3.27770395e-01, -1.93513560e-01,
        2.79884265e-02,  7.91253078e-02, -1.46074422e-01, -2.89390790e-01,
       -7.23135732e-04])

In [51]:
print('Mean squared error: %.2f' %mean_squared_error(y_test, y_pred))

Mean squared error: 0.06
